package vu.lt.myBatis.model;

import java.util.List;

public class BoardGame {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOARD_GAME.ID
     *
     * @mbg.generated Mon Apr 13 14:12:30 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BOARD_GAME.NAME
     *
     * @mbg.generated Mon Apr 13 14:12:30 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOARD_GAME.ID
     *
     * @return the value of PUBLIC.BOARD_GAME.ID
     *
     * @mbg.generated Mon Apr 13 14:12:30 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOARD_GAME.ID
     *
     * @param id the value for PUBLIC.BOARD_GAME.ID
     *
     * @mbg.generated Mon Apr 13 14:12:30 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BOARD_GAME.NAME
     *
     * @return the value of PUBLIC.BOARD_GAME.NAME
     *
     * @mbg.generated Mon Apr 13 14:12:30 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BOARD_GAME.NAME
     *
     * @param name the value for PUBLIC.BOARD_GAME.NAME
     *
     * @mbg.generated Mon Apr 13 14:12:30 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    private List<GameSession> gameSessions;

    public List<GameSession> getGameSessions() {
        return gameSessions;
    }

    public void setGameSessions(List<GameSession> gameSessions) {
        this.gameSessions = gameSessions;
    }
}