package vu.lt.myBatis.model;

public class GameSession {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME_SESSION.ID
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME_SESSION.SCORE
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    private Integer score;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME_SESSION.NAME
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.GAME_SESSION.BOARDGAME_ID
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    private Integer boardgameId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GAME_SESSION.ID
     *
     * @return the value of PUBLIC.GAME_SESSION.ID
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GAME_SESSION.ID
     *
     * @param id the value for PUBLIC.GAME_SESSION.ID
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GAME_SESSION.SCORE
     *
     * @return the value of PUBLIC.GAME_SESSION.SCORE
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    public Integer getScore() {
        return score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GAME_SESSION.SCORE
     *
     * @param score the value for PUBLIC.GAME_SESSION.SCORE
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    public void setScore(Integer score) {
        this.score = score;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GAME_SESSION.NAME
     *
     * @return the value of PUBLIC.GAME_SESSION.NAME
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GAME_SESSION.NAME
     *
     * @param name the value for PUBLIC.GAME_SESSION.NAME
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.GAME_SESSION.BOARDGAME_ID
     *
     * @return the value of PUBLIC.GAME_SESSION.BOARDGAME_ID
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    public Integer getBoardgameId() {
        return boardgameId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.GAME_SESSION.BOARDGAME_ID
     *
     * @param boardgameId the value for PUBLIC.GAME_SESSION.BOARDGAME_ID
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    public void setBoardgameId(Integer boardgameId) {
        this.boardgameId = boardgameId;
    }
}