package vu.lt.myBatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.myBatis.model.BoardGame;

@Mapper
public interface BoardGameMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOARD_GAME
     *
     * @mbg.generated Mon Apr 13 14:12:30 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOARD_GAME
     *
     * @mbg.generated Mon Apr 13 14:12:30 EEST 2020
     */
    int insert(BoardGame record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOARD_GAME
     *
     * @mbg.generated Mon Apr 13 14:12:30 EEST 2020
     */
    BoardGame selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOARD_GAME
     *
     * @mbg.generated Mon Apr 13 14:12:30 EEST 2020
     */
    List<BoardGame> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.BOARD_GAME
     *
     * @mbg.generated Mon Apr 13 14:12:30 EEST 2020
     */
    int updateByPrimaryKey(BoardGame record);
}