package vu.lt.myBatis.dao;

import java.util.List;

import org.mybatis.cdi.Mapper;
import vu.lt.myBatis.model.GameSession;

@Mapper
public interface GameSessionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME_SESSION
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME_SESSION
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    int insert(GameSession record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME_SESSION
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    GameSession selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME_SESSION
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    List<GameSession> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GAME_SESSION
     *
     * @mbg.generated Sun Apr 12 18:03:15 EEST 2020
     */
    int updateByPrimaryKey(GameSession record);
}